name: CI - Build & Push Docker

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  MONITOR_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/monitor:latest
  NGINX_IMAGE:   ${{ secrets.DOCKERHUB_USERNAME }}/nginx-proxy:latest

jobs:
  build-push:
    runs-on: self-hosted
    steps:
      # Passo 1: Fazer checkout do repositório
      - name: Checkout
        uses: actions/checkout@v4

      # Passo 2: Login no DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Passo 3: Decodificar o kubeconfig do segredo base64 e configurar o kubectl
      - name: Setup kubeconfig
        run: |
          echo "$KUBECONFIG_CONTENT" | base64 --decode > ~/.kube/config
          kubectl config use-context minikube  # Seleciona o contexto minikube

      # Passo 4: Build e Push da imagem do monitor
      - name: Build & Push monitor image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ env.MONITOR_IMAGE }}

      # Passo 5: Build e Push da imagem do nginx
      - name: Build & Push nginx image
        uses: docker/build-push-action@v6
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: ${{ env.NGINX_IMAGE }}
